name: docker

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: splitio-docker.jfrog.io
          username: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
          password: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set VERSION env
        run: echo "VERSION=$(cat splitio/version.go | grep 'Version =' | awk '{print $4}' | tr -d '"')" >> $GITHUB_ENV

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "infra/sidecar.Dockerfile"
          push: true
          tags: splitio-docker.jfrog.io/splitd/sidecar:latest,splitio-docker.jfrog.io/splitd/sidecar:${{ env.VERSION }}
