name: docker

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.run_number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Artifactory
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v2
        with:
          registry: splitio-docker.jfrog.io
          username: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
          password: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "infra/sidecar.Dockerfile"
          push: true
          push: ${{ github.event_name == 'push' }}
          tags: splitio-docker.jfrog.io/${{ github.event.repository.name }}/sidecar:${{ github.sha }}
